### ISSUE TITLE
Filtering user content

### ISSUE THREAD

**Issue by jvyden** [PlanetBunkum/Bunkum#5]
There should probably be some filtering in-place for user content, LBP *is* a kids game after all. User content refers to titles/descriptions, chat messages, comments, basically anything that a user types in a textbox.

What's our stance on this? How far should we go for default behavior - just terrible things like slurs or go all the way with your typical `fuck` and `shit`?

Not entirely sure how to implement this code-wise either.

Looking for comments/opinions.

**Comment by Arcadius2006** [comment]
let people say the fuck word

**Comment by Arcadius2006** [comment]
also, i feel like modded content is part of this issue? .ff files should be filtered out for safety

**Comment by jvyden** [comment]
> also, i feel like modded content is part of this issue?

No, just user content. That's a separate issue.

**Comment by jvyden** [comment]
Moving this to Bunkum - this should probably be a system implemented there

**Comment by jvyden** [comment]
This should now be trivial to implement code-wise with the introduction of services in `v3.0.0`. As such, I'll mark this as a good first issue.

**Comment by jvyden** [comment]
I made a wrapper around a library named [Profanity.Detector](https://github.com/stephenhaunts/ProfanityDetector/) under the name of [Bunkum.ProfanityFilter](https://github.com/LittleBigRefresh/Bunkum.ProfanityFilter)

I'll probably have to fork the original library and make some changes to it (there are some aspects of it I'm not happy with) before I ship it in Refresh, but for now here's an initial implementation

**Comment by jvyden** [comment]
There will definitely be some further things to consider - like how we can better implement this for filtering strings attached to classes instead of individual strings (right now I'd imagine it'd be pretty messy to do so) or having a toggle for certain users to be able to view filtered content. Naturally, the server maintainer should have better control over this sort of thing too.

**Comment by Beyley** [comment]
> There should probably be some filtering in-place for user content, LBP _is_ a kids game after all. User content refers to titles/descriptions, chat messages, comments, basically anything that a user types in a textbox.
> 
> What's our stance on this? How far should we go for default behavior - just terrible things like slurs or go all the way with your typical `fuck` and `shit`?
> 
> Not entirely sure how to implement this code-wise either.
> 
> Looking for comments/opinions.

i personally think by default words like `fuck` or `shit` should be allowed, but with a configurable "level" to block "all profanity", "just slurs", or "nothing", or places in between

**Comment by logantgt** [comment]
> i personally think by default words like ``fuck`` or ``shit`` should be allowed, but with a configurable "level" to block "all profanity", "just slurs", or "nothing", or places in between

Absolutely, it should be left up to the discretion of a server administrator.

Part of this problem is determining whether or not you want to allow for localized filters - the [Profanity.Detector](https://github.com/stephenhaunts/ProfanityDetector/) library does make it clear that it only intends to deal with filtering content in English. That said, it is a kid's game, the server/communities can run anywhere in the world, maybe it would be worth considering implementing a really dumb "catch all" Roblox level filter that allows a server admin to add swears in their language, given they are willing to accept way more false positives in order to provide a safe experience. It doesn't look like it would be too hard to implement this.

Scoping it out will make it easier to determine how to provide an admin with more granular control over the functionality of the filter.

**Comment by jvyden** [comment]
No longer in scope.
